import { useState, useEffect, useCallback, useRef } from "react";
import {
  FileText,
  BookOpen,
  Highlighter,
  Captions,
  BarChart3,
  Sparkles,
  Copy,
  Download,
  Share2,
  Edit3,
  RefreshCw,
  CheckCircle2,
  FolderPlus,
  List,
  X,
  Loader2,
  ChevronDown,
  Check,
} from "lucide-react";
import { cn } from "../../utils/cn";
import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import type { Note, FullSummaryData, GenerationEvent, TabType, AiConfig } from "../../types";

type TabId = "summary" | "original" | "highlights" | "script" | "visual" | "custom";

interface Tab {
  id: TabId;
  label: string;
  icon: React.ReactNode;
}

const TABS: Tab[] = [
  { id: "summary", label: "全文总结", icon: <FileText className="w-4 h-4" /> },
  { id: "original", label: "原文细读", icon: <BookOpen className="w-4 h-4" /> },
  { id: "highlights", label: "高光笔记", icon: <Highlighter className="w-4 h-4" /> },
  { id: "script", label: "字幕脚本", icon: <Captions className="w-4 h-4" /> },
  { id: "visual", label: "视觉化总结", icon: <BarChart3 className="w-4 h-4" /> },
  { id: "custom", label: "自定义总结", icon: <Sparkles className="w-4 h-4" /> },
];

// 标签页类型映射
const TAB_TYPE_MAPPING: Record<string, TabType> = {
  summary: "full_summary",
  original: "detailed_reading",
  highlights: "highlights",
  visual: "visual_summary",
  custom: "custom_summary",
};

interface NoteContentPanelProps {
  note: Note;
  onGenerationComplete?: () => void;
  aiConfigs: AiConfig[];
  currentModelId?: number | null; // 视频播放器右上角选择的模型ID
}

export function NoteContentPanel({ note, onGenerationComplete, aiConfigs, currentModelId }: NoteContentPanelProps) {
  const [activeTab, setActiveTab] = useState<TabId>("summary");

  // 跟踪已自动生成的笔记ID，避免重复触发
  const autoGeneratedNoteIds = useRef<Set<number>>(new Set());

  // 生成状态
  const [isGenerating, setIsGenerating] = useState(false);
  const [progress, setProgress] = useState<{ current: number; total: number; message: string }>({
    current: 0,
    total: 0,
    message: "",
  });
  const [completedTabs, setCompletedTabs] = useState<Set<TabType>>(new Set());
  const [failedTabs, setFailedTabs] = useState<Map<TabType, string>>(new Map());
  const [generationId, setGenerationId] = useState<string | null>(null);

  // 自定义提示词弹窗状态
  const [showPromptDialog, setShowPromptDialog] = useState(false);
  const [dialogTab, setDialogTab] = useState<"default" | "custom">("default");
  const [selectedModelId, setSelectedModelId] = useState<number>(note.model_id || aiConfigs[0]?.id || 0);

  // 自定义下拉框状态
  const [showModelDropdown, setShowModelDropdown] = useState(false);
  const [showLanguageDropdown, setShowLanguageDropdown] = useState(false);
  const modelDropdownRef = useRef<HTMLDivElement>(null);
  const languageDropdownRef = useRef<HTMLDivElement>(null);

  // 默认配置参数
  const [configLanguage, setConfigLanguage] = useState<"zh" | "en">("zh");
  const [configShowEmoji, setConfigShowEmoji] = useState(true);
  const [configShowTimestamp, setConfigShowTimestamp] = useState(false);
  const [configHighlightCount, setConfigHighlightCount] = useState(5);
  const [configSentenceLength, setConfigSentenceLength] = useState(30);

  // 自定义输入
  const [customPrompt, setCustomPrompt] = useState("");

  // 点击外部关闭下拉框
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (modelDropdownRef.current && !modelDropdownRef.current.contains(event.target as Node)) {
        setShowModelDropdown(false);
      }
      if (languageDropdownRef.current && !languageDropdownRef.current.contains(event.target as Node)) {
        setShowLanguageDropdown(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  // 解析全文总结JSON
  const parseFullSummary = useCallback((content: string | null): FullSummaryData | null => {
    if (!content) return null;
    try {
      return JSON.parse(content);
    } catch {
      return null;
    }
  }, []);

  // 开始生成笔记（一键生成全部）
  const handleGenerate = async () => {
    if (!note.model_id) {
      alert("请先选择AI模型");
      return;
    }

    try {
      const id = crypto.randomUUID();
      setGenerationId(id);
      setIsGenerating(true);
      setCompletedTabs(new Set());
      setFailedTabs(new Map());

      await new Promise(resolve => setTimeout(resolve, 50));

      await invoke("generate_note_content", {
        generationId: id,
        noteId: note.id,
        modelId: note.model_id,
        concurrent: true,
        regenerate: false,
        tabsToGenerate: [] as string[],
      });
    } catch (error) {
      setIsGenerating(false);
      setGenerationId(null);
      alert(`生成失败: ${error}`);
    }
  };

  // 监听生成事件
  useEffect(() => {
    if (!generationId) return;

    const unlistenPromises = [
      listen<GenerationEvent>(`note-generation-${generationId}`, (event) => {
        const data = event.payload;
        switch (data.status) {
          case "Starting":
            setProgress({ current: 0, total: data.total_tabs, message: "准备生成..." });
            break;

          case "TabStarted":
            setProgress((prev) => ({
              ...prev,
              message: `正在生成 ${data.tab_name}...`,
            }));
            break;

          case "TabProgress":
            setProgress({
              current: data.current,
              total: data.total,
              message: data.message,
            });
            break;

          case "TabCompleted":
            const completedTab = data.tab_type as TabType;
            setCompletedTabs((prev) => new Set([...prev, completedTab]));
            break;

          case "TabError":
            const failedTab = data.tab_type as TabType;
            setFailedTabs((prev) => new Map([...prev, [failedTab, data.error]]));
            break;

          case "AllCompleted":
            setIsGenerating(false);
            setGenerationId(null);
            setProgress({ current: data.total, total: data.total, message: "生成完成!" });
            onGenerationComplete?.();
            break;

          case "Aborted":
            setIsGenerating(false);
            setGenerationId(null);
            setProgress((prev) => ({ ...prev, message: "已中止" }));
            break;
        }
      }),
    ];

    return () => {
      Promise.all(unlistenPromises).then((unlisteners) => {
        unlisteners.forEach((u) => u());
      });
    };
  }, [generationId, onGenerationComplete]);

  // 自动生成：当组件挂载且没有全文总结时，自动开始生成（仅触发一次）
  useEffect(() => {
    if (autoGeneratedNoteIds.current.has(note.id)) {
      return;
    }

    const hasNoContent = !note.full_summary && !note.detailed_reading &&
                         !note.highlights && !note.visual_summary && !note.custom_summary;

    if (hasNoContent && note.model_id && !isGenerating) {
      autoGeneratedNoteIds.current.add(note.id);
      handleGenerate();
    }
  }, [note.id, note.full_summary, note.model_id]);

  // 检查标签页是否正在生成
  const isTabGenerating = (tabId: TabId): boolean => {
    const tabType = TAB_TYPE_MAPPING[tabId];
    if (!tabType) return false;
    return isGenerating && progress.message.includes(tabType === "full_summary" ? "全文总结" :
      tabType === "detailed_reading" ? "原文细读" :
      tabType === "highlights" ? "高光笔记" :
      tabType === "visual_summary" ? "视觉化总结" :
      "自定义总结");
  };

  // 检查标签页是否已完成生成
  const isTabCompleted = (tabId: TabId): boolean => {
    const tabType = TAB_TYPE_MAPPING[tabId];
    if (!tabType) return false;
    return completedTabs.has(tabType);
  };

  // 检查标签页是否生成失败
  const getTabError = (tabId: TabId): string | undefined => {
    const tabType = TAB_TYPE_MAPPING[tabId];
    if (!tabType) return undefined;
    return failedTabs.get(tabType);
  };

  // 打开自定义提示词弹窗
  const openPromptDialog = () => {
    // 优先使用视频播放器右上角选择的模型，其次是笔记关联的模型，最后是第一个配置
    setSelectedModelId(currentModelId || note.model_id || aiConfigs[0]?.id || 0);
    setDialogTab("default");
    setConfigLanguage("zh");
    setConfigShowEmoji(true);
    setConfigShowTimestamp(false);
    setConfigHighlightCount(5);
    setConfigSentenceLength(30);
    setCustomPrompt("");
    setShowPromptDialog(true);
  };

  // 根据配置生成动态提示词
  const generateDynamicPrompt = useCallback((): string => {
    const langText = configLanguage === "zh" ? "中文" : "英文";
    const emojiInstruction = configShowEmoji
      ? "每个亮点必须包含emoji字段，填入一个合适的表情符号"
      : "每个亮点的emoji字段留空（设为空字符串）";
    const timestampInstruction = configShowTimestamp
      ? "，并在timestamp字段中标注该亮点对应的视频时间戳（格式如 00:01:23）"
      : "";

    // 根据是否需要时间戳动态生成JSON结构示例
    const highlightExample = configShowTimestamp
      ? `{"emoji": "${configShowEmoji ? "🔥" : ""}", "title": "亮点标题", "description": "详细描述", "timestamp": "00:01:23"}`
      : `{"emoji": "${configShowEmoji ? "🔥" : ""}", "title": "亮点标题", "description": "详细描述"}`;

    return `你是一个专业的视频内容分析师。请分析以下视频字幕，生成一份结构化的全文总结。

输出要求：
1. 必须以JSON格式输出，不要有任何其他文字（包括markdown代码块标记）
2. 使用${langText}输出所有内容
3. JSON结构如下：
{
  "abstract": "100-150字的摘要段落，概括视频核心内容",
  "highlights": [
    ${highlightExample},
    ...
    （共${configHighlightCount}个亮点）
  ],
  "tags": ["标签1", "标签2", "标签3"],
  "qa_pairs": [
    {"question": "问题", "answer": "回答"},
    ...
    （3个Q&A，如果是技术教学类视频）
  ],
  "thoughts": [
    "引导性的思考问题",
    ...
    （2个思考问题，如果是应用介绍类视频）
  ],
  "glossary": [
    {"term": "术语", "explanation": "解释"},
    ...
    （5个关键术语）
  ]
}

内容要求：
- abstract: 简洁概括视频核心内容，每句话不超过${configSentenceLength}字
- highlights: 提取最重要的${configHighlightCount}个知识点/亮点，${emojiInstruction}${timestampInstruction}
- tags: 3-5个相关标签，用于分类和搜索
- qa_pairs: 技术教学类视频需要3个常见问题及答案，应用介绍类可省略（设为null）
- thoughts: 应用介绍类视频需要2个引导性思考问题，技术教学类可省略（设为null）
- glossary: 提取5个关键术语并解释`;
  }, [configLanguage, configShowEmoji, configShowTimestamp, configHighlightCount, configSentenceLength]);

  // 执行生成
  const handleCustomGenerate = async () => {
    if (!selectedModelId) {
      alert("请选择AI模型");
      return;
    }

    let finalPrompt = "";

    if (dialogTab === "custom") {
      finalPrompt = customPrompt;
      if (!finalPrompt) {
        alert("请输入自定义提示词");
        return;
      }
    } else {
      finalPrompt = generateDynamicPrompt();
    }

    setShowPromptDialog(false);

    try {
      const id = crypto.randomUUID();
      setGenerationId(id);
      setIsGenerating(true);
      setCompletedTabs(new Set());
      setFailedTabs(new Map());

      await new Promise(resolve => setTimeout(resolve, 50));

      await invoke("generate_note_content", {
        generationId: id,
        noteId: note.id,
        modelId: selectedModelId,
        concurrent: true,
        regenerate: true,
        tabsToGenerate: [TAB_TYPE_MAPPING[activeTab]],
        customPrompt: finalPrompt,
      });
    } catch (error) {
      setIsGenerating(false);
      setGenerationId(null);
      alert(`生成失败: ${error}`);
    }
  };

  return (
    <div className="flex flex-col h-full bg-white dark:bg-vnote-card rounded-lg border border-slate-200 dark:border-vnote-border overflow-hidden">
      {/* 标签页头部 */}
      <div className="border-b border-slate-200 dark:border-vnote-border">
        <div className="flex flex-wrap">
          {TABS.map((tab) => {
            const generating = isTabGenerating(tab.id);
            const completed = isTabCompleted(tab.id);
            const error = getTabError(tab.id);

            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={cn(
                  "flex items-center gap-1.5 px-4 py-3 text-sm font-medium border-b-2 -mb-px transition-colors relative",
                  activeTab === tab.id
                    ? "border-blue-500 text-blue-500"
                    : "border-transparent text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200"
                )}
              >
                {tab.icon}
                {tab.label}
                {generating && (
                  <span className="w-2 h-2 bg-blue-500 rounded-full animate-ping" />
                )}
                {completed && !generating && (
                  <CheckCircle2 className="w-3 h-3 text-green-500" />
                )}
                {error && !generating && (
                  <X className="w-3 h-3 text-red-500" />
                )}
              </button>
            );
          })}
        </div>
      </div>

      {/* 工具栏 */}
      <div className="flex items-center justify-between px-4 py-2 border-b border-slate-200 dark:border-vnote-border">
        <div className="flex items-center gap-2">
          <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-slate-600 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-vnote-hover rounded-lg transition-colors">
            <FolderPlus className="w-4 h-4" />
            添加合集
          </button>
          <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-slate-600 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-vnote-hover rounded-lg transition-colors">
            <List className="w-4 h-4" />
            章节
            <span className="ml-1 text-xs text-slate-400">(6)</span>
          </button>
        </div>

        <div className="flex items-center gap-1">
          <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-slate-600 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-vnote-hover rounded-lg transition-colors">
            <Copy className="w-4 h-4" />
            复制
          </button>
          <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-slate-600 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-vnote-hover rounded-lg transition-colors">
            <Download className="w-4 h-4" />
            下载
          </button>
          <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-blue-500 hover:bg-blue-50 dark:hover:bg-blue-500/10 rounded-lg transition-colors">
            <Share2 className="w-4 h-4" />
            分享
          </button>
        </div>
      </div>

      {/* 次级工具栏 */}
      <div className="flex items-center justify-between px-4 py-2 border-b border-slate-200 dark:border-vnote-border bg-slate-50 dark:bg-vnote-surface">
        <div className="flex items-center gap-2">
          <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-slate-600 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-vnote-hover rounded-lg transition-colors">
            <Edit3 className="w-4 h-4" />
            编辑
          </button>
          <span className="text-slate-300 dark:text-slate-600">|</span>
          <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-slate-600 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-vnote-hover rounded-lg transition-colors">
            思维导图
          </button>
        </div>
        <button
          onClick={openPromptDialog}
          className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-slate-600 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-vnote-hover rounded-lg transition-colors"
        >
          <RefreshCw className="w-4 h-4" />
          重新总结
        </button>
      </div>

      {/* 内容区域 */}
      <div className="flex-1 overflow-y-auto p-6">
        {activeTab === "summary" && (
          <SummaryContent
            summaryData={parseFullSummary(note.full_summary)}
            rawContent={note.full_summary}
            isGenerating={isTabGenerating("summary")}
          />
        )}
        {activeTab === "original" && (
          <TabContent
            content={note.detailed_reading}
            isGenerating={isTabGenerating("original")}
            emptyMessage="原文细读内容将在AI分析后生成"
          />
        )}
        {activeTab === "highlights" && (
          <HighlightsContent
            content={note.highlights}
            isGenerating={isTabGenerating("highlights")}
            emptyMessage="暂无高光笔记"
          />
        )}
        {activeTab === "script" && <ScriptContent subtitlePath={note.subtitle_path} />}
        {activeTab === "visual" && (
          <TabContent
            content={note.visual_summary}
            isGenerating={isTabGenerating("visual")}
            emptyMessage="视觉化总结 (Beta) - 即将推出"
          />
        )}
        {activeTab === "custom" && (
          <TabContent
            content={note.custom_summary}
            isGenerating={isTabGenerating("custom")}
            emptyMessage="自定义总结 - 根据您的需求定制总结内容"
          />
        )}
      </div>

      {/* 自定义总结弹窗 */}
      {showPromptDialog && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={() => setShowPromptDialog(false)}>
          <div className="bg-white dark:bg-vnote-card rounded-2xl shadow-2xl w-[600px] max-w-[90vw]" onClick={e => e.stopPropagation()}>
            {/* 标题和关闭按钮 */}
            <div className="flex items-center justify-between px-8 pt-6 pb-4">
              <h3 className="text-xl font-semibold text-slate-900 dark:text-slate-100 flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-blue-500" />
                重新生成总结
              </h3>
              <button
                onClick={() => setShowPromptDialog(false)}
                className="p-1.5 hover:bg-slate-100 dark:hover:bg-slate-700 rounded-lg transition-colors"
              >
                <X className="w-5 h-5 text-slate-500" />
              </button>
            </div>

            {/* 标签切换 */}
            <div className="px-8">
              <div className="flex gap-1.5 p-1 bg-slate-100 dark:bg-slate-800 rounded-xl">
                <button
                  onClick={() => setDialogTab("default")}
                  className={`flex-1 px-4 py-2.5 text-sm font-medium rounded-lg transition-all ${
                    dialogTab === "default"
                      ? "bg-white dark:bg-slate-700 text-blue-600 dark:text-blue-400 shadow-sm"
                      : "text-slate-600 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-200"
                  }`}
                >
                  默认配置
                </button>
                <button
                  onClick={() => setDialogTab("custom")}
                  className={`flex-1 px-4 py-2.5 text-sm font-medium rounded-lg transition-all ${
                    dialogTab === "custom"
                      ? "bg-white dark:bg-slate-700 text-blue-600 dark:text-blue-400 shadow-sm"
                      : "text-slate-600 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-200"
                  }`}
                >
                  自定义总结
                </button>
              </div>
            </div>

            {/* 默认配置标签页内容 */}
            {dialogTab === "default" && (
              <div className="px-8 py-6">
                {/* 两列布局 */}
                <div className="grid grid-cols-2 gap-x-10 gap-y-5">
                  {/* 大语言模型 */}
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-medium text-slate-700 dark:text-slate-300">大语言模型</span>
                    <div className="relative" ref={modelDropdownRef}>
                      <button
                        type="button"
                        onClick={() => setShowModelDropdown(!showModelDropdown)}
                        className="w-44 px-3 py-2 pr-10 rounded-xl border border-slate-200 dark:border-slate-600 bg-white dark:bg-slate-800 text-sm text-slate-900 dark:text-slate-100 font-medium text-left focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent cursor-pointer hover:border-slate-300 dark:hover:border-slate-500 transition-all truncate"
                      >
                        {aiConfigs.find(c => c.id === selectedModelId)?.title || "选择模型"}
                      </button>
                      <ChevronDown className={`absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400 pointer-events-none transition-transform ${showModelDropdown ? "rotate-180" : ""}`} />
                      {showModelDropdown && (
                        <div className="absolute z-50 mt-2 w-56 right-0 bg-white dark:bg-slate-800 rounded-xl shadow-lg border border-slate-200 dark:border-slate-700 py-1 max-h-60 overflow-auto">
                          {aiConfigs.map(config => (
                            <button
                              key={config.id}
                              type="button"
                              onClick={() => {
                                setSelectedModelId(config.id);
                                setShowModelDropdown(false);
                              }}
                              className={`w-full px-4 py-2.5 text-left text-sm flex items-center justify-between hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors ${
                                selectedModelId === config.id ? "text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/20" : "text-slate-700 dark:text-slate-300"
                              }`}
                            >
                              <span className="truncate">{config.title}</span>
                              {selectedModelId === config.id && <Check className="w-4 h-4 flex-shrink-0 ml-2" />}
                            </button>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>

                  {/* 输出语言 */}
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-medium text-slate-700 dark:text-slate-300">输出语言</span>
                    <div className="relative" ref={languageDropdownRef}>
                      <button
                        type="button"
                        onClick={() => setShowLanguageDropdown(!showLanguageDropdown)}
                        className="w-32 px-3 py-2 pr-10 rounded-xl border border-slate-200 dark:border-slate-600 bg-white dark:bg-slate-800 text-sm text-slate-900 dark:text-slate-100 font-medium text-left focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent cursor-pointer hover:border-slate-300 dark:hover:border-slate-500 transition-all"
                      >
                        {configLanguage === "zh" ? "中文" : "English"}
                      </button>
                      <ChevronDown className={`absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400 pointer-events-none transition-transform ${showLanguageDropdown ? "rotate-180" : ""}`} />
                      {showLanguageDropdown && (
                        <div className="absolute z-50 mt-2 w-32 right-0 bg-white dark:bg-slate-800 rounded-xl shadow-lg border border-slate-200 dark:border-slate-700 py-1">
                          {[
                            { value: "zh", label: "中文" },
                            { value: "en", label: "English" },
                          ].map(lang => (
                            <button
                              key={lang.value}
                              type="button"
                              onClick={() => {
                                setConfigLanguage(lang.value as "zh" | "en");
                                setShowLanguageDropdown(false);
                              }}
                              className={`w-full px-4 py-2.5 text-left text-sm flex items-center justify-between hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors ${
                                configLanguage === lang.value ? "text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/20" : "text-slate-700 dark:text-slate-300"
                              }`}
                            >
                              <span>{lang.label}</span>
                              {configLanguage === lang.value && <Check className="w-4 h-4 flex-shrink-0 ml-2" />}
                            </button>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>

                  {/* 是否显示Emoji */}
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-medium text-slate-700 dark:text-slate-300">是否显示Emoji</span>
                    <button
                      onClick={() => setConfigShowEmoji(!configShowEmoji)}
                      className={`relative w-14 h-7 rounded-full transition-all duration-200 ease-in-out ${
                        configShowEmoji ? "bg-blue-500" : "bg-slate-200 dark:bg-slate-600"
                      }`}
                    >
                      <span
                        className={`absolute top-1 w-5 h-5 bg-white rounded-full shadow-md transition-all duration-200 ease-in-out ${
                          configShowEmoji ? "left-8" : "left-1"
                        }`}
                      />
                    </button>
                  </div>

                  {/* 是否显示时间戳 */}
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-medium text-slate-700 dark:text-slate-300">是否显示时间戳</span>
                    <button
                      onClick={() => setConfigShowTimestamp(!configShowTimestamp)}
                      className={`relative w-14 h-7 rounded-full transition-all duration-200 ease-in-out ${
                        configShowTimestamp ? "bg-blue-500" : "bg-slate-200 dark:bg-slate-600"
                      }`}
                    >
                      <span
                        className={`absolute top-1 w-5 h-5 bg-white rounded-full shadow-md transition-all duration-200 ease-in-out ${
                          configShowTimestamp ? "left-8" : "left-1"
                        }`}
                      />
                    </button>
                  </div>

                  {/* 要点个数 */}
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-medium text-slate-700 dark:text-slate-300">要点个数</span>
                    <div className="flex items-center gap-3 w-40">
                      <input
                        type="range"
                        min="1"
                        max="15"
                        value={configHighlightCount}
                        onChange={e => setConfigHighlightCount(Number(e.target.value))}
                        className="flex-1 h-2 bg-slate-200 dark:bg-slate-600 rounded-full appearance-none cursor-pointer accent-blue-500"
                      />
                      <span className="text-sm font-semibold text-slate-700 dark:text-slate-300 w-6 text-center">{configHighlightCount}</span>
                    </div>
                  </div>

                  {/* 句子长短 */}
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-medium text-slate-700 dark:text-slate-300">句子长短</span>
                    <div className="flex items-center gap-3 w-40">
                      <input
                        type="range"
                        min="10"
                        max="40"
                        step="5"
                        value={configSentenceLength}
                        onChange={e => setConfigSentenceLength(Number(e.target.value))}
                        className="flex-1 h-2 bg-slate-200 dark:bg-slate-600 rounded-full appearance-none cursor-pointer accent-blue-500"
                      />
                      <span className="text-sm font-semibold text-slate-700 dark:text-slate-300 w-7 text-center">{configSentenceLength}</span>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* 自定义总结标签页内容 */}
            {dialogTab === "custom" && (
              <div className="px-8 py-6">
                {/* 大语言模型 */}
                <div className="flex items-center justify-between mb-5">
                  <span className="text-sm font-medium text-slate-700 dark:text-slate-300">大语言模型</span>
                  <div className="relative" ref={modelDropdownRef}>
                    <button
                      type="button"
                      onClick={() => setShowModelDropdown(!showModelDropdown)}
                      className="w-48 px-3 py-2 pr-10 rounded-xl border border-slate-200 dark:border-slate-600 bg-white dark:bg-slate-800 text-sm text-slate-900 dark:text-slate-100 font-medium text-left focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent cursor-pointer hover:border-slate-300 dark:hover:border-slate-500 transition-all truncate"
                    >
                      {aiConfigs.find(c => c.id === selectedModelId)?.title || "选择模型"}
                    </button>
                    <ChevronDown className={`absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400 pointer-events-none transition-transform ${showModelDropdown ? "rotate-180" : ""}`} />
                    {showModelDropdown && (
                      <div className="absolute z-50 mt-2 w-56 right-0 bg-white dark:bg-slate-800 rounded-xl shadow-lg border border-slate-200 dark:border-slate-700 py-1 max-h-60 overflow-auto">
                        {aiConfigs.map(config => (
                          <button
                            key={config.id}
                            type="button"
                            onClick={() => {
                              setSelectedModelId(config.id);
                              setShowModelDropdown(false);
                            }}
                            className={`w-full px-4 py-2.5 text-left text-sm flex items-center justify-between hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors ${
                              selectedModelId === config.id ? "text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/20" : "text-slate-700 dark:text-slate-300"
                            }`}
                          >
                            <span className="truncate">{config.title}</span>
                            {selectedModelId === config.id && <Check className="w-4 h-4 flex-shrink-0 ml-2" />}
                          </button>
                        ))}
                      </div>
                    )}
                  </div>
                </div>

                {/* 自定义提示词输入 */}
                <div>
                  <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-3">自定义提示词</label>
                  <textarea
                    value={customPrompt}
                    onChange={e => setCustomPrompt(e.target.value)}
                    placeholder="输入您的自定义提示词...例如：请用小学生能理解的语言总结这个视频的核心内容"
                    rows={8}
                    className="w-full px-4 py-3 rounded-xl border border-slate-300 dark:border-slate-500 bg-white dark:bg-slate-700 text-sm text-slate-900 dark:text-slate-100 resize-none focus:outline-none focus:ring-2 focus:ring-blue-500 placeholder:text-slate-400"
                  />
                </div>
              </div>
            )}

            {/* 底部按钮 */}
            <div className="flex gap-3 px-8 pb-6 pt-2">
              <button
                onClick={() => setShowPromptDialog(false)}
                className="flex-1 px-4 py-2.5 text-sm font-medium text-slate-600 dark:text-slate-400 border border-slate-200 dark:border-slate-600 hover:bg-slate-100 dark:hover:bg-vnote-hover rounded-xl transition-colors"
              >
                取消
              </button>
              <button
                onClick={handleCustomGenerate}
                disabled={dialogTab === "custom" && !customPrompt}
                className="flex-1 px-4 py-2.5 text-sm font-medium bg-blue-600 text-white rounded-xl hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                <Sparkles className="w-4 h-4" />
                开始生成
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// 全文总结内容
function SummaryContent({
  summaryData,
  rawContent,
  isGenerating,
}: {
  summaryData: FullSummaryData | null;
  rawContent: string | null;
  isGenerating: boolean;
}) {
  if (isGenerating) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-center">
          <Loader2 className="w-8 h-8 text-blue-500 animate-spin mx-auto mb-3" />
          <p className="text-sm text-slate-500">正在生成全文总结...</p>
        </div>
      </div>
    );
  }

  if (!rawContent) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-center">
          <Loader2 className="w-8 h-8 text-blue-500 animate-spin mx-auto mb-3" />
          <p className="text-sm text-slate-500">正在生成全文总结...</p>
        </div>
      </div>
    );
  }

  if (!summaryData) {
    return (
      <div className="prose prose-sm dark:prose-invert max-w-none">
        <pre className="whitespace-pre-wrap text-sm text-slate-600 dark:text-slate-300">
          {rawContent}
        </pre>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* 摘要 */}
      <section>
        <h2 className="text-lg font-semibold text-slate-800 dark:text-slate-100 mb-3">摘要</h2>
        <p className="text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
          {summaryData.abstract}
        </p>
      </section>

      {/* 亮点 */}
      <section>
        <h2 className="text-lg font-semibold text-slate-800 dark:text-slate-100 mb-3">亮点</h2>
        <ul className="space-y-3">
          {summaryData.highlights.map((item, index) => (
            <li key={index} className="flex items-start gap-3 text-sm text-slate-600 dark:text-slate-300">
              <span className="text-xl mt-0.5">{item.emoji}</span>
              <div className="flex-1">
                <div className="flex items-center gap-2">
                  <h3 className="font-medium text-slate-700 dark:text-slate-200">{item.title}</h3>
                  {item.timestamp && (
                    <span className="px-2 py-0.5 text-xs bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 rounded-md font-mono">
                      {item.timestamp}
                    </span>
                  )}
                </div>
                <p className="text-slate-500 dark:text-slate-400 mt-1">{item.description}</p>
              </div>
            </li>
          ))}
        </ul>
      </section>

      {/* 标签 */}
      <section>
        <div className="flex flex-wrap gap-2">
          {summaryData.tags.map((tag, index) => (
            <span
              key={index}
              className="px-3 py-1 text-xs bg-slate-100 dark:bg-vnote-surface text-slate-600 dark:text-slate-400 rounded-full"
            >
              #{tag}
            </span>
          ))}
        </div>
      </section>

      {/* 疑问解答（可选） */}
      {summaryData.qa_pairs && summaryData.qa_pairs.length > 0 && (
        <section>
          <h2 className="text-lg font-semibold text-slate-800 dark:text-slate-100 mb-3">疑问解答</h2>
          <div className="space-y-4">
            {summaryData.qa_pairs.map((pair, index) => (
              <div key={index}>
                <h3 className="text-sm font-medium text-slate-700 dark:text-slate-200 mb-2">
                  Q: {pair.question}
                </h3>
                <p className="text-sm text-slate-600 dark:text-slate-400 pl-4">
                  A: {pair.answer}
                </p>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* 思考问题（可选） */}
      {summaryData.thoughts && summaryData.thoughts.length > 0 && (
        <section>
          <h2 className="text-lg font-semibold text-slate-800 dark:text-slate-100 mb-3">思考</h2>
          <div className="space-y-2">
            {summaryData.thoughts.map((thought, index) => (
              <p key={index} className="text-sm text-slate-600 dark:text-slate-400">
                Q: {thought}
              </p>
            ))}
          </div>
        </section>
      )}

      {/* 术语表 */}
      <section>
        <h2 className="text-lg font-semibold text-slate-800 dark:text-slate-100 mb-3">术语表</h2>
        <div className="space-y-2">
          {summaryData.glossary.map((item, index) => (
            <div key={index} className="text-sm">
              <span className="font-medium text-slate-700 dark:text-slate-200">
                {item.term}：
              </span>
              <span className="text-slate-600 dark:text-slate-400">{item.explanation}</span>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}

// 通用标签页内容
function TabContent({
  content,
  isGenerating,
  emptyMessage,
}: {
  content: string | null;
  isGenerating: boolean;
  emptyMessage: string;
}) {
  if (isGenerating) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-center">
          <Loader2 className="w-8 h-8 text-blue-500 animate-spin mx-auto mb-3" />
          <p className="text-sm text-slate-500">正在生成...</p>
        </div>
      </div>
    );
  }

  if (!content) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-slate-400">
        <p>{emptyMessage}</p>
      </div>
    );
  }

  return (
    <div className="prose prose-slate dark:prose-invert max-w-none">
      <div
        className="whitespace-pre-wrap text-sm text-slate-600 dark:text-slate-300"
        dangerouslySetInnerHTML={{ __html: content }}
      />
    </div>
  );
}

// 高光笔记内容
function HighlightsContent({
  content,
  isGenerating,
  emptyMessage,
}: {
  content: string | null;
  isGenerating: boolean;
  emptyMessage: string;
}) {
  if (isGenerating) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-center">
          <Loader2 className="w-8 h-8 text-blue-500 animate-spin mx-auto mb-3" />
          <p className="text-sm text-slate-500">正在生成高光笔记...</p>
        </div>
      </div>
    );
  }

  if (!content) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-slate-400">
        <Highlighter className="w-12 h-12 mb-4 opacity-50" />
        <p>{emptyMessage}</p>
        <p className="text-sm mt-2">观看视频时添加高光笔记</p>
      </div>
    );
  }

  return (
    <div className="prose prose-slate dark:prose-invert max-w-none">
      <div
        className="whitespace-pre-wrap text-sm text-slate-600 dark:text-slate-300"
        dangerouslySetInnerHTML={{ __html: content }}
      />
    </div>
  );
}

// 字幕脚本内容 - 直接读取字幕文件
function ScriptContent({ subtitlePath }: { subtitlePath: string | null }) {
  const [subtitleContent, setSubtitleContent] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!subtitlePath) {
      setSubtitleContent(null);
      return;
    }

    setLoading(true);
    setError(null);

    invoke<string>("read_file_content", { path: subtitlePath })
      .then((content) => {
        setSubtitleContent(content);
      })
      .catch((err) => {
        setError(`无法读取字幕文件: ${err}`);
      })
      .finally(() => {
        setLoading(false);
      });
  }, [subtitlePath]);

  if (!subtitlePath) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-slate-400">
        <Captions className="w-12 h-12 mb-4 opacity-50" />
        <p>未上传字幕文件</p>
        <p className="text-sm mt-2">上传视频时可选择添加字幕文件</p>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full text-slate-400">
        <p>加载字幕中...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-slate-400">
        <p className="text-red-400">{error}</p>
      </div>
    );
  }

  return (
    <div className="prose prose-slate dark:prose-invert max-w-none">
      <pre className="whitespace-pre-wrap text-sm text-slate-600 dark:text-slate-300 font-mono bg-slate-50 dark:bg-vnote-surface p-4 rounded-lg">
        {subtitleContent}
      </pre>
    </div>
  );
}
